name: country_select_app
description: A country selector app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_info_plus: ^9.1.2
  dio: ^5.4.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  package_info_plus: ^5.0.1
  

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true